services:
  - type: web
    name: music-player-backend
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: JIOSAAVN_BASE_URL
        value: https://jiosaavn-api.pradeepreddypalagiri.workers.dev
    healthCheckPath: /api/health