services:
  - type: web
    name: music-player-backend
    runtime: docker
    plan: free
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SAAVN_BASE_URL
        value: https://api.piped.private.coffee
    healthCheckPath: /api/health