services:
  - type: web
    name: music-player-backend
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JIOSAAVN_BASE_URL
        value: https://jiosaavn-api.pradeepreddypalagiri.workers.dev/api
    healthCheckPath: /api/health